// Code generated by MockGen. DO NOT EDIT.
// Source: thing_service.go

// Package capture is a generated GoMock package.
package capture

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockThingService is a mock of ThingService interface.
type MockThingService struct {
	ctrl     *gomock.Controller
	recorder *MockThingServiceMockRecorder
}

// MockThingServiceMockRecorder is the mock recorder for MockThingService.
type MockThingServiceMockRecorder struct {
	mock *MockThingService
}

// NewMockThingService creates a new mock instance.
func NewMockThingService(ctrl *gomock.Controller) *MockThingService {
	mock := &MockThingService{ctrl: ctrl}
	mock.recorder = &MockThingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThingService) EXPECT() *MockThingServiceMockRecorder {
	return m.recorder
}

// AddThing mocks base method.
func (m *MockThingService) AddThing(thing *Thing) (*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThing", thing)
	ret0, _ := ret[0].(*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddThing indicates an expected call of AddThing.
func (mr *MockThingServiceMockRecorder) AddThing(thing interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThing", reflect.TypeOf((*MockThingService)(nil).AddThing), thing)
}

// GetThings mocks base method.
func (m *MockThingService) GetThings() ([]*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThings")
	ret0, _ := ret[0].([]*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThings indicates an expected call of GetThings.
func (mr *MockThingServiceMockRecorder) GetThings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThings", reflect.TypeOf((*MockThingService)(nil).GetThings))
}

// MarkThingAsProcessed mocks base method.
func (m *MockThingService) MarkThingAsProcessed(thingID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkThingAsProcessed", thingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkThingAsProcessed indicates an expected call of MarkThingAsProcessed.
func (mr *MockThingServiceMockRecorder) MarkThingAsProcessed(thingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkThingAsProcessed", reflect.TypeOf((*MockThingService)(nil).MarkThingAsProcessed), thingID)
}

// MockAddThingUseCase is a mock of AddThingUseCase interface.
type MockAddThingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAddThingUseCaseMockRecorder
}

// MockAddThingUseCaseMockRecorder is the mock recorder for MockAddThingUseCase.
type MockAddThingUseCaseMockRecorder struct {
	mock *MockAddThingUseCase
}

// NewMockAddThingUseCase creates a new mock instance.
func NewMockAddThingUseCase(ctrl *gomock.Controller) *MockAddThingUseCase {
	mock := &MockAddThingUseCase{ctrl: ctrl}
	mock.recorder = &MockAddThingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddThingUseCase) EXPECT() *MockAddThingUseCaseMockRecorder {
	return m.recorder
}

// AddThing mocks base method.
func (m *MockAddThingUseCase) AddThing(thing Thing) (*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThing", thing)
	ret0, _ := ret[0].(*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddThing indicates an expected call of AddThing.
func (mr *MockAddThingUseCaseMockRecorder) AddThing(thing interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThing", reflect.TypeOf((*MockAddThingUseCase)(nil).AddThing), thing)
}

// MockGetThingUseCase is a mock of GetThingUseCase interface.
type MockGetThingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetThingUseCaseMockRecorder
}

// MockGetThingUseCaseMockRecorder is the mock recorder for MockGetThingUseCase.
type MockGetThingUseCaseMockRecorder struct {
	mock *MockGetThingUseCase
}

// NewMockGetThingUseCase creates a new mock instance.
func NewMockGetThingUseCase(ctrl *gomock.Controller) *MockGetThingUseCase {
	mock := &MockGetThingUseCase{ctrl: ctrl}
	mock.recorder = &MockGetThingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetThingUseCase) EXPECT() *MockGetThingUseCaseMockRecorder {
	return m.recorder
}

// GetThingByID mocks base method.
func (m *MockGetThingUseCase) GetThingByID(id int) (*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThingByID", id)
	ret0, _ := ret[0].(*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThingByID indicates an expected call of GetThingByID.
func (mr *MockGetThingUseCaseMockRecorder) GetThingByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThingByID", reflect.TypeOf((*MockGetThingUseCase)(nil).GetThingByID), id)
}

// MockGetThingsUseCase is a mock of GetThingsUseCase interface.
type MockGetThingsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetThingsUseCaseMockRecorder
}

// MockGetThingsUseCaseMockRecorder is the mock recorder for MockGetThingsUseCase.
type MockGetThingsUseCaseMockRecorder struct {
	mock *MockGetThingsUseCase
}

// NewMockGetThingsUseCase creates a new mock instance.
func NewMockGetThingsUseCase(ctrl *gomock.Controller) *MockGetThingsUseCase {
	mock := &MockGetThingsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetThingsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetThingsUseCase) EXPECT() *MockGetThingsUseCaseMockRecorder {
	return m.recorder
}

// GetThings mocks base method.
func (m *MockGetThingsUseCase) GetThings() ([]Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThings")
	ret0, _ := ret[0].([]Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThings indicates an expected call of GetThings.
func (mr *MockGetThingsUseCaseMockRecorder) GetThings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThings", reflect.TypeOf((*MockGetThingsUseCase)(nil).GetThings))
}

// MockUpdateThingStatusUseCase is a mock of UpdateThingStatusUseCase interface.
type MockUpdateThingStatusUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateThingStatusUseCaseMockRecorder
}

// MockUpdateThingStatusUseCaseMockRecorder is the mock recorder for MockUpdateThingStatusUseCase.
type MockUpdateThingStatusUseCaseMockRecorder struct {
	mock *MockUpdateThingStatusUseCase
}

// NewMockUpdateThingStatusUseCase creates a new mock instance.
func NewMockUpdateThingStatusUseCase(ctrl *gomock.Controller) *MockUpdateThingStatusUseCase {
	mock := &MockUpdateThingStatusUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateThingStatusUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateThingStatusUseCase) EXPECT() *MockUpdateThingStatusUseCaseMockRecorder {
	return m.recorder
}

// UpdateThingStatus mocks base method.
func (m *MockUpdateThingStatusUseCase) UpdateThingStatus(id int, status Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThingStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThingStatus indicates an expected call of UpdateThingStatus.
func (mr *MockUpdateThingStatusUseCaseMockRecorder) UpdateThingStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThingStatus", reflect.TypeOf((*MockUpdateThingStatusUseCase)(nil).UpdateThingStatus), id, status)
}
