// Code generated by MockGen. DO NOT EDIT.
// Source: tihng_repository.go

// Package capture is a generated GoMock package.
package capture

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockThingRepository is a mock of ThingRepository interface.
type MockThingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThingRepositoryMockRecorder
}

// MockThingRepositoryMockRecorder is the mock recorder for MockThingRepository.
type MockThingRepositoryMockRecorder struct {
	mock *MockThingRepository
}

// NewMockThingRepository creates a new mock instance.
func NewMockThingRepository(ctrl *gomock.Controller) *MockThingRepository {
	mock := &MockThingRepository{ctrl: ctrl}
	mock.recorder = &MockThingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThingRepository) EXPECT() *MockThingRepositoryMockRecorder {
	return m.recorder
}

// AddThing mocks base method.
func (m *MockThingRepository) AddThing(thing *Thing) (*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThing", thing)
	ret0, _ := ret[0].(*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddThing indicates an expected call of AddThing.
func (mr *MockThingRepositoryMockRecorder) AddThing(thing interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThing", reflect.TypeOf((*MockThingRepository)(nil).AddThing), thing)
}

// GetThingByID mocks base method.
func (m *MockThingRepository) GetThingByID(id int) (*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThingByID", id)
	ret0, _ := ret[0].(*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThingByID indicates an expected call of GetThingByID.
func (mr *MockThingRepositoryMockRecorder) GetThingByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThingByID", reflect.TypeOf((*MockThingRepository)(nil).GetThingByID), id)
}

// GetThings mocks base method.
func (m *MockThingRepository) GetThings() ([]*Thing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThings")
	ret0, _ := ret[0].([]*Thing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThings indicates an expected call of GetThings.
func (mr *MockThingRepositoryMockRecorder) GetThings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThings", reflect.TypeOf((*MockThingRepository)(nil).GetThings))
}
