// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package workflow is a generated GoMock package.
package workflow

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActionService is a mock of ActionService interface.
type MockActionService struct {
	ctrl     *gomock.Controller
	recorder *MockActionServiceMockRecorder
}

// MockActionServiceMockRecorder is the mock recorder for MockActionService.
type MockActionServiceMockRecorder struct {
	mock *MockActionService
}

// NewMockActionService creates a new mock instance.
func NewMockActionService(ctrl *gomock.Controller) *MockActionService {
	mock := &MockActionService{ctrl: ctrl}
	mock.recorder = &MockActionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionService) EXPECT() *MockActionServiceMockRecorder {
	return m.recorder
}

// CreateActionFromClarified mocks base method.
func (m *MockActionService) CreateActionFromClarified(data ClarifiedData) (*Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActionFromClarified", data)
	ret0, _ := ret[0].(*Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActionFromClarified indicates an expected call of CreateActionFromClarified.
func (mr *MockActionServiceMockRecorder) CreateActionFromClarified(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActionFromClarified", reflect.TypeOf((*MockActionService)(nil).CreateActionFromClarified), data)
}

// DeleteAction mocks base method.
func (m *MockActionService) DeleteAction(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAction", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAction indicates an expected call of DeleteAction.
func (mr *MockActionServiceMockRecorder) DeleteAction(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAction", reflect.TypeOf((*MockActionService)(nil).DeleteAction), id)
}

// GetActionByID mocks base method.
func (m *MockActionService) GetActionByID(id int) (*Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionByID", id)
	ret0, _ := ret[0].(*Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionByID indicates an expected call of GetActionByID.
func (mr *MockActionServiceMockRecorder) GetActionByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionByID", reflect.TypeOf((*MockActionService)(nil).GetActionByID), id)
}

// GetActions mocks base method.
func (m *MockActionService) GetActions() []Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActions")
	ret0, _ := ret[0].([]Action)
	return ret0
}

// GetActions indicates an expected call of GetActions.
func (mr *MockActionServiceMockRecorder) GetActions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActions", reflect.TypeOf((*MockActionService)(nil).GetActions))
}

// Save mocks base method.
func (m *MockActionService) Save(action Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockActionServiceMockRecorder) Save(action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockActionService)(nil).Save), action)
}

// UpdateAction mocks base method.
func (m *MockActionService) UpdateAction(id int, action Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAction", id, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAction indicates an expected call of UpdateAction.
func (mr *MockActionServiceMockRecorder) UpdateAction(id, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAction", reflect.TypeOf((*MockActionService)(nil).UpdateAction), id, action)
}

// UpdateActionStatus mocks base method.
func (m *MockActionService) UpdateActionStatus(id int, status Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionStatus indicates an expected call of UpdateActionStatus.
func (mr *MockActionServiceMockRecorder) UpdateActionStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionStatus", reflect.TypeOf((*MockActionService)(nil).UpdateActionStatus), id, status)
}
