// Code generated by MockGen. DO NOT EDIT.
// Source: action_repository.go

// Package workflow is a generated GoMock package.
package workflow

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActionRepository is a mock of ActionRepository interface.
type MockActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActionRepositoryMockRecorder
}

// MockActionRepositoryMockRecorder is the mock recorder for MockActionRepository.
type MockActionRepositoryMockRecorder struct {
	mock *MockActionRepository
}

// NewMockActionRepository creates a new mock instance.
func NewMockActionRepository(ctrl *gomock.Controller) *MockActionRepository {
	mock := &MockActionRepository{ctrl: ctrl}
	mock.recorder = &MockActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionRepository) EXPECT() *MockActionRepositoryMockRecorder {
	return m.recorder
}

// AddAction mocks base method.
func (m *MockActionRepository) AddAction(action *Action) (*Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAction", action)
	ret0, _ := ret[0].(*Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAction indicates an expected call of AddAction.
func (mr *MockActionRepositoryMockRecorder) AddAction(action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAction", reflect.TypeOf((*MockActionRepository)(nil).AddAction), action)
}

// DeleteAction mocks base method.
func (m *MockActionRepository) DeleteAction(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAction", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAction indicates an expected call of DeleteAction.
func (mr *MockActionRepositoryMockRecorder) DeleteAction(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAction", reflect.TypeOf((*MockActionRepository)(nil).DeleteAction), id)
}

// GetActionByID mocks base method.
func (m *MockActionRepository) GetActionByID(id int) (*Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionByID", id)
	ret0, _ := ret[0].(*Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActionByID indicates an expected call of GetActionByID.
func (mr *MockActionRepositoryMockRecorder) GetActionByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionByID", reflect.TypeOf((*MockActionRepository)(nil).GetActionByID), id)
}

// GetActions mocks base method.
func (m *MockActionRepository) GetActions() ([]*Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActions")
	ret0, _ := ret[0].([]*Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActions indicates an expected call of GetActions.
func (mr *MockActionRepositoryMockRecorder) GetActions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActions", reflect.TypeOf((*MockActionRepository)(nil).GetActions))
}

// UpdateAction mocks base method.
func (m *MockActionRepository) UpdateAction(action *Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAction", action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAction indicates an expected call of UpdateAction.
func (mr *MockActionRepositoryMockRecorder) UpdateAction(action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAction", reflect.TypeOf((*MockActionRepository)(nil).UpdateAction), action)
}
