// Code generated by mockery v2.53.5. DO NOT EDIT.

package usermocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Issuer is an autogenerated mock type for the Issuer type
type Issuer struct {
	mock.Mock
}

type Issuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Issuer) EXPECT() *Issuer_Expecter {
	return &Issuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function with given fields: userId, email, duration
func (_m *Issuer) Issue(userId int, email string, duration time.Duration) (string, error) {
	ret := _m.Called(userId, email, duration)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, time.Duration) (string, error)); ok {
		return rf(userId, email, duration)
	}
	if rf, ok := ret.Get(0).(func(int, string, time.Duration) string); ok {
		r0 = rf(userId, email, duration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, string, time.Duration) error); ok {
		r1 = rf(userId, email, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Issuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type Issuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userId int
//   - email string
//   - duration time.Duration
func (_e *Issuer_Expecter) Issue(userId interface{}, email interface{}, duration interface{}) *Issuer_Issue_Call {
	return &Issuer_Issue_Call{Call: _e.mock.On("Issue", userId, email, duration)}
}

func (_c *Issuer_Issue_Call) Run(run func(userId int, email string, duration time.Duration)) *Issuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *Issuer_Issue_Call) Return(_a0 string, _a1 error) *Issuer_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Issuer_Issue_Call) RunAndReturn(run func(int, string, time.Duration) (string, error)) *Issuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewIssuer creates a new instance of Issuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Issuer {
	mock := &Issuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
