// Code generated by mockery v2.53.5. DO NOT EDIT.

package usermocks

import (
	user "yangdongju/gtd_todo/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// LoginUsecase is an autogenerated mock type for the LoginUsecase type
type LoginUsecase struct {
	mock.Mock
}

type LoginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginUsecase) EXPECT() *LoginUsecase_Expecter {
	return &LoginUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: request
func (_m *LoginUsecase) Login(request user.LoginRequest) (*user.LoginResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(user.LoginRequest) (*user.LoginResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(user.LoginRequest) *user.LoginResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(user.LoginRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type LoginUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - request user.LoginRequest
func (_e *LoginUsecase_Expecter) Login(request interface{}) *LoginUsecase_Login_Call {
	return &LoginUsecase_Login_Call{Call: _e.mock.On("Login", request)}
}

func (_c *LoginUsecase_Login_Call) Run(run func(request user.LoginRequest)) *LoginUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(user.LoginRequest))
	})
	return _c
}

func (_c *LoginUsecase_Login_Call) Return(_a0 *user.LoginResponse, _a1 error) *LoginUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoginUsecase_Login_Call) RunAndReturn(run func(user.LoginRequest) (*user.LoginResponse, error)) *LoginUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginUsecase creates a new instance of LoginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginUsecase {
	mock := &LoginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
