// Code generated by mockery v2.53.5. DO NOT EDIT.

package usermocks

import (
	user "yangdongju/gtd_todo/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// SignUpUsecase is an autogenerated mock type for the SignUpUsecase type
type SignUpUsecase struct {
	mock.Mock
}

type SignUpUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *SignUpUsecase) EXPECT() *SignUpUsecase_Expecter {
	return &SignUpUsecase_Expecter{mock: &_m.Mock}
}

// signUp provides a mock function with given fields: request
func (_m *SignUpUsecase) signUp(request user.SignUpRequest) (*user.SignUpResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for signUp")
	}

	var r0 *user.SignUpResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(user.SignUpRequest) (*user.SignUpResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(user.SignUpRequest) *user.SignUpResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.SignUpResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(user.SignUpRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignUpUsecase_signUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'signUp'
type SignUpUsecase_signUp_Call struct {
	*mock.Call
}

// signUp is a helper method to define mock.On call
//   - request user.SignUpRequest
func (_e *SignUpUsecase_Expecter) signUp(request interface{}) *SignUpUsecase_signUp_Call {
	return &SignUpUsecase_signUp_Call{Call: _e.mock.On("signUp", request)}
}

func (_c *SignUpUsecase_signUp_Call) Run(run func(request user.SignUpRequest)) *SignUpUsecase_signUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(user.SignUpRequest))
	})
	return _c
}

func (_c *SignUpUsecase_signUp_Call) Return(_a0 *user.SignUpResponse, _a1 error) *SignUpUsecase_signUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SignUpUsecase_signUp_Call) RunAndReturn(run func(user.SignUpRequest) (*user.SignUpResponse, error)) *SignUpUsecase_signUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewSignUpUsecase creates a new instance of SignUpUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignUpUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignUpUsecase {
	mock := &SignUpUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
