// Code generated by mockery v2.53.5. DO NOT EDIT.

package usermocks

import (
	user "yangdongju/gtd_todo/internal/user"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// FindUserByEmail provides a mock function with given fields: email
func (_m *UserRepository) FindUserByEmail(email string) (*user.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*user.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type UserRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *UserRepository_Expecter) FindUserByEmail(email interface{}) *UserRepository_FindUserByEmail_Call {
	return &UserRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *UserRepository_FindUserByEmail_Call) Run(run func(email string)) *UserRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_FindUserByEmail_Call) Return(_a0 *user.User, _a1 error) *UserRepository_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindUserByEmail_Call) RunAndReturn(run func(string) (*user.User, error)) *UserRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: _a0
func (_m *UserRepository) Save(_a0 *user.User) (*user.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*user.User) (*user.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*user.User) *user.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*user.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type UserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 *user.User
func (_e *UserRepository_Expecter) Save(_a0 interface{}) *UserRepository_Save_Call {
	return &UserRepository_Save_Call{Call: _e.mock.On("Save", _a0)}
}

func (_c *UserRepository_Save_Call) Run(run func(_a0 *user.User)) *UserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*user.User))
	})
	return _c
}

func (_c *UserRepository_Save_Call) Return(_a0 *user.User, _a1 error) *UserRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Save_Call) RunAndReturn(run func(*user.User) (*user.User, error)) *UserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
